### ISSUE TITLE
Checking object exists in Islandora

### ISSUE THREAD

**Issue by mark-cooper** [lyrasis/aspace-islandora#5]
https://github.com/lyrasis/aspace-islandora/blob/master/indexer/indexer.rb#L28-L33

@jonathangreen before we were using login method to check whether object exists (including if restricted), now it may exist but not be accessible using anonymous GET request. How do you want to handle? Respond to GET for `/islandora/aspace/object/$PID`?

**Comment by jonathangreen** [comment]
Do we even need to do that check? If that check is removed and instead we try: 
https://github.com/lyrasis/aspace-islandora/blob/master/indexer/indexer.rb#L36

That PUT request will return a 404 if the object doesn't exist, that way we could do one request instead of two. I don't see any harm in trying the PUT request if all the other tests pass.

**Comment by mark-cooper** [comment]
Sure, I'll go with that :+1:
